name: nuxeo_automation
version: 0.0.2
author: Nelson Silva <nelson.silva@inevo.pt>
description: A Nuxeo Automation Client
homepage: https://github.com/nelsonsilva/nuxeo-dart-automation
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.10.0 <0.11.0'
  logging: '>=0.9.0 <0.10.0'
  logging_handlers: '>=0.8.0 <0.9.0'
dev_dependencies:
  hop: '>=0.30.3 <0.31.0'
  hop_docgen: '>=0.1.2+2 < 0.2.0'
  unittest: '>=0.10.1+2 <0.11.0'

