name: nuxeo
version: 0.0.1
author: Nelson Silva <nelson.silva@inevo.pt>
description: A Nuxeo Automation Client
dependencies:
  browser: any
  crypto: any
  http: any
  logging: any
  logging_handlers: any
  unittest: any
