name: nuxeo_automation
version: 0.0.1
author: Nelson Silva <nelson.silva@inevo.pt>
description: A Nuxeo Automation Client
homepage: https://github.com/nelsonsilva/nuxeo-dart-automation
dependencies:
  browser: any
  crypto: any
  http: any
  logging: any
  logging_handlers: any
dev_dependencies:
  hop: '>=0.24.1'
  unittest: any
